export const DefaultPizza = [
  {
    id: 1,
    name: 'Kiss Jóska',
    zip: 3600,
    city: 'Ózd',
    address1: 'Vasvár',
    address2: 7,
    telephonePrefix: 30,
    telephone: '1234567',
    isSelected: false,
  },
  {
    id: 2,
    name: 'Németh Edina',
    zip: 3600,
    city: 'Ózd',
    address1: 'Nemzetőr',
    address2: 11,
    telephonePrefix: 30,
    telephone: '5553670',
    isSelected: false,
  },
  {
    id: 3,
    name: 'Nagy Ferenc',
    zip: 3500,
    city: 'Miskolc',
    address1: 'Ady Endre',
    address2: 18,
    telephonePrefix: 20,
    telephone: '5145236',
    isSelected: false,
  },
  {
    id: 4,
    name: 'Szabó Franciska',
    zip: 3300,
    city: 'Eger',
    address1: 'Petőfi Sándor',
    address2: 202,
    telephonePrefix: 70,
    telephone: '7654321',
    isSelected: false,
  },
];
